name = "Hugo Docs"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://gohugo.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Ryan Watters"
  homepage = "ryanwatters.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
